# Generated by Django 3.1 on 2020-09-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerscanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.CharField(max_length=150)),
                ('vul_name', models.CharField(max_length=300)),
                ('risk', models.CharField(max_length=20)),
                ('alert', models.CharField(max_length=100)),
                ('decryption', models.CharField(max_length=500)),
                ('solution', models.CharField(max_length=500)),
                ('evidence', models.CharField(max_length=350)),
                ('other', models.CharField(max_length=600)),
                ('scan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerscanner.scandata')),
            ],
        ),
    ]
