# Generated by Django 3.1 on 2020-09-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerscanner', '0002_vulnerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerdata',
            name='decryption',
            field=models.CharField(max_length=1200),
        ),
    ]
