# Generated by Django 3.1 on 2020-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerscanner', '0003_auto_20200903_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerdata',
            name='alert',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='vulnerdata',
            name='evidence',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='vulnerdata',
            name='other',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='vulnerdata',
            name='solution',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vulnerdata',
            name='urls',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='vulnerdata',
            name='vul_name',
            field=models.CharField(max_length=500),
        ),
    ]
