# Generated by Django 3.1 on 2020-09-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerscanner', '0004_auto_20200903_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerdata',
            name='decryption',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='vulnerdata',
            name='evidence',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='vulnerdata',
            name='other',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='vulnerdata',
            name='solution',
            field=models.CharField(max_length=3000),
        ),
    ]
