# Generated by Django 3.1 on 2020-09-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerscanner', '0006_auto_20200904_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerdata',
            name='other',
            field=models.TextField(),
        ),
    ]
