# Generated by Django 3.1 on 2020-09-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerscanner', '0007_auto_20200904_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_name', models.CharField(max_length=50)),
            ],
        ),
    ]
