# Generated by Django 3.1 on 2020-09-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerscanner', '0008_contextdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextdata',
            name='con_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
